
tasks:
  - init: |
      curl -L https://dl.dagger.io/dagger/install.sh | sh 
    command: |
      $PWD/bin/dagger project update
      $PWD/bin/dagger do build
vscode:
  extensions:
    - golang.go
